'use strict';

function includeAllRoutes(app, passport) {
  require('./user-api.js')(app, passport);
  require('./login-api.js')(app, passport);
  require('./department-api.js')(app, passport);
  require('./designation-api.js')(app, passport);
  require('./role-api.js')(app, passport);
  require('./company-api.js')(app, passport);
  require('./loan-schema-api.js')(app, passport);
  require('./loan-default-type-api.js')(app, passport);
  require('./add-new-loan-template-api.js')(app, passport);
  require('./product-api.js')(app, passport);
  require('./productlist-configuration-api.js')(app, passport);
  require('./tokens-api.js')(app, passport);
  require('./partner-api.js')(app, passport);
  require('./services-api.js')(app, passport);
  require('./loan-request-api.js')(app, passport);
  require('./borrower-info-api.js')(app, passport);
  require('./disbursements-channel-config.js')(app, passport);
  require('./loan-document-api.js')(app, passport);
  require('./credit-limit-api.js')(app, passport);
  require('./kz-pan-api.js')(app, passport);
  require('./aadhar-offline-api.js')(app, passport);
  require('./cl-repay-and-credit.js')(app, passport);
  require('./loc-drawdown-report-api')(app, passport);
  //require("./ckyc-api.js")(app, passport);
  require('./postman-collection-schema-api.js')(app, passport);
  require('./credit-grid-api.js')(app, passport);
  // require("./bureau-grid-api.js")(app, passport);
  require('./company-services-api.js')(app, passport);
  require('./bank-acc-number-api.js')(app, passport);
  require('./driver-license-kyc-api.js')(app, passport);
  require('./voterid-api.js')(app, passport);
  require('./loan-details-api.js')(app, passport);
  // require("./banking-entity-api.js")(app, passport);
  require('./loan-process-flow-api.js')(app, passport);
  require('./wallet-ledger-api.js')(app, passport);
  require('./reconcile-api.js')(app, passport);
  require('./third-party-institutes-api.js')(app, passport);
  require('./advance-ai-bureau-api.js')(app, passport);
  require('./loan-disbursement-api.js')(app, passport);
  require('./dues-api.js')(app, passport);
  require('./otp-api.js')(app, passport);
  require('./repayment-schedule-dump-api.js')(app, passport);
  require('./composite-disbursement-api.js')(app, passport);
  require('./kooliza-disbursement-api.js')(app, passport);
  require('./loan-setting-api.js')(app, passport);
  require('./crif-api.js')(app, passport);
  require('./disbursement-api.js')(app, passport);
  require('./repayment-api.js')(app, passport);
  require('./cibil-v3-api.js')(app, passport);
  require('./loandocument-template-api.js')(app, passport);
  require('./loan-activities-api.js')(app, passport);
  require('./aadhaar-api.js')(app, passport);
  require('./digitap-verification-api.js')(app, passport);
  require('./ckyc-api.js')(app, passport);
  require('./cashfree-api.js')(app, passport);
  require('./mca-api.js')(app, passport);
  require('./pan-advance-kyc-api.js')(app, passport);
  require('./cibil-verification-api.js')(app, passport);
  require('./bureau-scorecard-api')(app, passport);
  require('./test-disbursement-api.js')(app, passport);
  require('./broadcast_event_master.js')(app, passport);
  require('./subscribe_event.js')(app, passport);
  require('./experian-api.js')(app, passport);
  require('./kz-pan-details-api.js')(app, passport);
  require('./enhanced-review-api.js')(app, passport);
  require('./disbursement-ledger-api.js')(app, passport);
  require('./webhook-api.js')(app, passport);
  require('./gst-api.js')(app, passport);
  require('./disbursement-report-api.js')(app, passport);
  require('./ocr-kyc-api.js')(app, passport);
  require('./repayment-report-api.js')(app, passport);
  require('./kyc-compliance-report-api.js')(app, passport);
  require('./bureau-scorecard-cache-api.js')(app, passport);
  require('./repayment-due-report-api.js')(app, passport);
  require('./repayment-schedule-report-api.js')(app, passport);
  require('./kz-alerts-api.js')(app, passport);
  require('./ckyc-api-v2.js')(app, passport);
  require('./collateral-api.js')(app, passport);
  require('./kz-name-api.js')(app, passport);
  require('./kz-address-api.js')(app, passport);
  require('./line-of-credit-api.js')(app, passport);
  require('./bre-api.js')(app, passport);
  require('./loc-repayment-record-api')(app, passport);
  require('./vehicle-rc-api.js')(app, passport);
  require('./repayment-api-v2.js')(app, passport);
  require('./gst-verification-api.js')(app, passport);
  require('./crif-soft-pull-api.js')(app, passport);
  require('./cibil-cache-api.js')(app, passport);
  require('./subvention-invoice-report-api.js')(app, passport);
  require('./enach-api')(app, passport);
  require('./dpd-report-api.js')(app, passport);
  require('./okyc-webhook-api.js')(app, passport);
  require('./repayment-approve-api.js')(app, passport);
  require('./co-lender-selector-api.js')(app, passport);
  require('./borrower-history-api.js')(app, passport);
  require('./nach-presentation-api.js')(app, passport);
  require('./co-lender-profile-api.js')(app, passport);
  require('./charges-api')(app, passport);
  require('./product-type-api.js')(app, passport);
  require('./bureau-scorecard-api-v2.js')(app, passport);
  require('./ascore-api.js')(app, passport);
  require('./recon-details-api')(app, passport);
  require('./foreclosure-request-api.js')(app, passport);
  require('./insurance-policy-api')(app, passport);
  require('./bank-details-api.js')(app, passport);
  require('./partner-analytics-api.js')(app, passport);
  require('./insurance-config-api.js')(app, passport);
  require('./co-lender-loan-api.js')(app, passport);
  require('./installment-repayment-recon-report-api.js')(app, passport);
  require('./gst-parsing-api.js')(app, passport);
  require('./co-lender-repayment-schedule-api.js')(app, passport);
  require('./co-lender-transaction-history-api.js')(app, passport);
  require('./co-lender-decision-api.js')(app, passport);
  require('./insurance-billing-report-api.js')(app, passport);
  require('./sub-loan-data-api.js')(app, passport);
  require('./loc-drawdown-emi-api.js')(app, passport);
  require('./recalibrate-sanction-api.js')(app, passport);
  require('./co-lender-report-api')(app, passport);
  require('./collection-api.js')(app, passport);
  require('./borrower-report-api.js')(app, passport);
  require('./access-metrix-api.js')(app, passport);
  require('./cibil-report-download-api.js')(app, passport);
  require('./utr-file-upload-api.js')(app, passport);
  require('./cams-details-api.js')(app, passport);
  require('./cbi-reports-api.js')(app, passport);
  require('./kyc/aadhaar_pan_xml_parser.js')(app, passport);
  require('./ckyc-report-api.js')(app, passport);
  require('./kyc/ckyc_operations_api.js')(app, passport);
  require('./collection-report-api.js')(app, passport);
  require('./screen-report-api.js')(app, passport);
  require('./status-logs-api.js')(app, passport);
  require('./nach-repayment-api.js')(app, passport);
  require('./nsdl-pan-api.js')(app, passport);
  require('./otp-api-v2.js')(app, passport);
  require('./ckyc-file-upload.js')(app, passport);
  require('./co-lender-callback-api.js')(app, passport);
  require('./foreclosure/v2/foreclosure-api.js')(app, passport);
  require('./settlement/settlement-api.js')(app, passport);
  require('./service-usage-report-api.js')(app, passport);
  require('./refund-webhook-api.js')(app, passport);
  require('./P2P/p2p-api.js')(app, passport);
  require('./P2P/p2p-net-investable-update-api.js')(app, passport);
  require('./third-party-apis/estamp/estamp-api.js')(app, passport);
  require('./borrower-misc-data-api.js')(app, passport);
  require('./kyc/kyc_document_api.js')(app, passport);
  require('./fetch-enum-fields-api.js')(app, passport);
  require('./third-party-apis/pennydrop/pennydrop-v2-api.js')(app, passport);
  require('./reports/leads-daily-report-api.js')(app, passport);
  require('./reports/loans-daily-report-api.js')(app, passport);
  require('./loc/loc-drawdown-api.js')(app, passport);
  require('./loan-state-api.js')(app, passport);
  require('./SOA/soa-api.js')(app, passport);
  require('./auto-loan-manual-cases-api.js')(app, passport);
  require('./refund-api.js')(app, passport);
  require('./refund-report-api.js')(app, passport);
  require('./P2P/p2p-reports')(app, passport);
  require('./insurance-report-api.js')(app, passport);
  require('./productSchemeMapping/productSchemeMapping')(app, passport);
  require('./scheme-api.js')(app, passport);
  require('./abfl-bre-status-callback-api.js')(app, passport);
  require('./master-bank-details.js')(app, passport);
  require('./cibil-report-api.js')(app, passport);
  require('./disbursement-inprogress-report-api.js')(app, passport);
  require('./udhyam-aadhar-webhook-api.js')(app, passport);
  require('./a-score-request-api.js')(app, passport);
  require('./cashcollaterals/cash-collaterals-api.js')(app, passport);
  require('./partner-document-api.js')(app, passport);
  require('./abfl-mrp-polling-callback-api.js')(app, passport);
  require('../modules/disbursement/routes.js')(app, passport);
  require('./repayment-file-api.js')(app, passport);
  require('./anchor-api.js')(app, passport);
  require('./collection/collection-api.js')(app, passport);
  require('./anchor-document-api.js')(app, passport);
  require('./third-party-apis/enach/enach-status-api.js')(app, passport);
  require("./co-lending/co-lending-repayment-api.js") (app, passport);
  require('./callback/icici-callback-api') (app, passport);
  require('./collection-bank-account-master-api.js') (app, passport);
  require('./reports/report-request-api.js') (app, passport);
  require('../modules/collection/routes')(app, passport);
  require('./third-party-apis/commercial-cibil/commercial-cibil-api.js')(app,passport);
  require('./customer-api.js') (app, passport);
  require('./validation-api.js') (app, passport);
  require('./third-party-apis/enach/presentment-api.js') (app, passport);
  require('./third-party-apis/enach/bulk-upload-api.js') (app, passport);
  require('./third-party-apis/enach/reports-api.js') (app, passport);
  require('./leegality-e-sign/leegality-esign.js')(app, passport);
  // msme routes
  require('../modules/msme/routes')(app, passport);
  require('../modules/third-party-api-services/routes')(app, passport);
  require('./forceClose/force-close-api.js')(app, passport);
  require("../routes/third-party-apis/bbps/bbps-api") (app, passport)
  //tds refund
  require('./tds-refund-api.js')(app, passport);
}

module.exports = function (app, passport) {
  includeAllRoutes(app, passport);
};
